Catalog2 3
usvladis/FakeNFT_team3 pull request #57
Opened 2024-10-21 15:02 UTC by slenbder

## Проведена работа по Модулю 2: Реализация бизнес-логики и функциональности

### Задачи:

- **Реализовал загрузку данных для экрана каталога**
    
    - _Описание:_
        - Создал модели данных `CollectionModel` и `NFTModel`.
        - Реализовал сетевой слой (`NetworkService`) для выполнения запросов.
        - Реализовал запрос к серверу для получения списка коллекций.
        - Спарсил получение данных.
        - Реализовал обновление `CatalogViewModel` и уведомление `CatalogViewController` об обновлении данных.
    - _Оценка:_ **5 часов**; _Факт:_ 4 часа.
    
- **Реализовал сортировку коллекций**
    
    - _Описание:_
        - Добавил кнопку сортировки в `CatalogViewController`.
        - Реализовал отображение вариантов сортировки.
        - Обновил `CatalogViewModel` для применения выбранного способа сортировки к данным.
        - Разработал сохранение выбранного способа сортировки локально с использованием `UserDefaults`.
        - Реализовал восстановление сохраненного способа сортировки при запуске приложения.
    - _Оценка:_ **5 часов**; _Факт:_ 4 часа.
    
- **Реализовал переходы между экранами**
    
    - _Описание:_
        - Настроил переход из `CatalogViewController` в `CollectionViewController` при выборе коллекции.
        - Настроил переход из `CollectionViewController` в `NFTDetailViewController` при выборе NFT.
        - Реализовал открытие сайта автора коллекции в `WKWebView` при нажатии на его имя.
    - _Оценка:_ **2 часа**; _Факт:_ 1 часа.
    
- **Подготовка к ревью**
    
    - _Описание:_ Провел тестирование реализованной функциональности, убедился в корректной работе, подготовил код к проверке.
    - _Оценка:_ **1 час**; _Факт:_ 1 час.

2024-10-23 11:57 UTC, usvladis commented on FakeNFT/Scenes /Catalog/Catalog Screen/View/CatalogViewController.swift
> +                self.NFTTableView.reloadData()
Ты везде в коде используешь [weak self], но тут пропустил. Лучше использовать чтобы избежать потенциальную утечку памяти

2024-10-23 11:57 UTC, usvladis commented on FakeNFT/Scenes /Catalog/Catalog Screen/View/CatalogViewController.swift
> +        cell.prepareForReuse()
Метод prepareForReuse вызывается явно в коде, что необычно. Этот метод не должен вызываться вручную, его вызывает сама таблица при переиспользовании ячеек. Вместо этого, стоит переместить код очистки в метод prepareForReuse() внутри самой ячейки.

2024-10-23 11:57 UTC, usvladis commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +            guard let self = self else {return}
ProgressHUD.dismiss() лучше вызвать сразу и закрыть индикатор при любом исходе, так как в случае ошибки индикатор загрузки будет висеть

2024-10-23 11:57 UTC, usvladis commented on FakeNFT/Scenes /Catalog/Collection Screen /View/AuthorWebView.swift
> +    }
@objc private func didTapWebViewBackButton() {
    if webView.canGoBack {
        webView.goBack()
    } else {
        navigationController?.popViewController(animated: true)
    }
}

Кнопка “Назад” возвращает пользователя на предыдущий экран, а не на предыдущую страницу внутри WebView. Я бы использовал реализацию выше, в случае если webView состоит из нескольких экранов внутри

2024-10-23 11:57 UTC, usvladis commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +        viewModel.fetchNFTs {
Снова [weak self] во избежание возможных утечек

2024-10-24 11:32 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/View/CatalogViewController.swift
> +                self.NFTTableView.reloadData()
Верно подмечено, исправил!

2024-10-24 11:38 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +        viewModel.fetchNFTs {
Исправил

2024-10-24 11:42 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/AuthorWebView.swift
> +    }
Верно, так действительно логичнее. Исправил

2024-10-24 11:46 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +            guard let self = self else {return}
Исправил! Так же, кстати, избавился от DispatchGroup, потому что в данном контексте у нас только одна асинхронная операция

2024-10-24 11:53 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/View/CatalogViewController.swift
> +        cell.prepareForReuse()
Действительно, это было лишнее. Исправил!

2024-10-25 08:07 UTC, Kirchberg requested changes

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +    var reloadTableView: (() -> Void)? { get set }
В целом это могла быть тоже функция, как это сделано для `fetchCollections`, было бы хорошо привести к одному виду. В данном случае ближе всего подходит функция с `completion: @escaping () -> Void`

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +class CatalogViewModel: CatalogViewModelProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае комплятор будет быстрее находить адрес ячейки памяти при вызове функции.

Эта тема про диспетчеризацию, если интересно, можно почитать здесь:
https://habr.com/ru/post/673400/
https://habr.com/ru/company/simbirsoft/blog/673636/

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +    private let sortOptionKey = "sortOptionKey"
Внутри `class CatalogViewModel: CatalogViewModelProtocol` использование `UserDefaults.standard.set(option.rawValue, forKey: sortOptionKey)` не совсем соответствует принципам **SOLID**, а именно **Принцип единственной ответственности (Single Responsibility Principle)**. 

Логика, связанная с сохранением и получением данных, не должна находиться в `ViewModel`, так как это увеличивает количество ответственностей у этого класса и усложняет его тестирование и поддержку.

Рекомендация: лучше вынести работу с `UserDefaults` в отдельную обертку (например, `SortOptionStorage`), где эта логика будет инкапсулирована. Таким образом, `CatalogViewModel` будет знать только о `SortOptionStorage` и не будет заботиться о деталях, связанных с хранилищем.

```swift
final class SortOptionStorage {

    func save(option: SortOption) {
        // Сохранение опции сортировки в UserDefaults
        ...
    }

    func retrieveSortOption() -> SortOption? {
        // Извлечение опции сортировки из UserDefaults
        ...
    }

    private let sortOptionKey = "sortOptionKey"
    
}
```

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /Model/CollectionModel.swift
> +final class CollectionModel {
`final class CollectionModel` можно улучшить, добавив реализацию протокола (например, `CatalogCollectionModelProtocol`). Это сделает код более гибким и облегчит тестирование.

Также название `CollectionModel` слишком общее и может ввести в заблуждение других разработчиков, подразумевая универсальное назначение. Было бы хорошо переименовать класс в более специфичное название, связанное с каталогом, например, `CatalogCollectionModel`, чтобы явно отразить его предназначение.

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /Model/CollectionModel.swift
> +        dispatchGroup.leave()
⚠️ Не совсем корректное использование `dispatchGroup`. У нас получается так, что в dispatchGroup мы входим каждый раз, когда у нас появляется id, но выходим только один раз, когда обработка закончилась.

`dispatchGroup.leave()` следует переместить в замыкание `loadNft`, чтобы оно вызывалось после завершения загрузки каждой NFT. Также `completion(.success(nfts))` нужно вызывать после завершения всех задач в группе, используя `dispatchGroup.notify`.

```swift
func loadCollection(idArrys: [String], completion: @escaping NftsCompletion) {
    var nfts: Nfts = []
    ProgressHUD.show()
    let dispatchGroup = DispatchGroup()
    
    for id in idArrys {
        dispatchGroup.enter()
        loadNft(id: id) { (result: Result<Nft, any Error>) in
            switch result {
            case .success(let nft):
                nfts.append(nft)
            case .failure(let error):
                print(error.localizedDescription)
            }
            dispatchGroup.leave() // Переносим вызов сюда
        }
    }
    
    dispatchGroup.notify(queue: .main) {
        ProgressHUD.dismiss()
        completion(.success(nfts))
    }
}
```

Давай поправим это место

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /Model/CollectionModel.swift
> +                    print(error.localizedDescription)
Вместо `print` для отладки, было бы хорошо использовать специальный написанный сервис логирования. Это повысит удобство тестирования и гибкость при отладке.

**Это было бы хорошим челленджом для тебя. Рекомендую почитать данную статью, она очень интересная**: https://www.avanderlee.com/debugging/oslog-unified-logging/

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +                .cacheOriginalImage
Молодец хорошее и красивое использование ✨

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +
В функциях после объявления функции и по окончанию лучше не оставлять пустые строки, было бы хорошо убрать их, так обычно делают внутри объявления структур, особенно если мы хотим визуально отделить данные внутри этих структур по смыслу

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +        print(url)
Было бы хорошо убрать :)

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +final class CollectionViewModel: CollectionViewModelProtocol {
Было бы хорошо также переименовать на более связанное с каталогом

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        dispatchGroup.enter()
Не используется, было бы хорошо убрать

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +    }
Не совсем понимаю, чем отличается от `CollectionModel`. Кажется как раз и запутались в названии классов.

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        }
⚠️ Логика работы с `dispatchGroup` в данном случае избыточна, так как у нас есть метод `loadCollection` внутри `collectionModel`, который как раз эту обработку и делает.

2024-10-25 08:07 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +    }
Вместо того чтобы `CollectionModel` напрямую взаимодействовал с `NetworkClient`, можно создать сервис, который будет управлять запросами к сети и обрабатывать общие функции, такие как прогресс, ошибки.

```swift
protocol NftServiceProtocol {
    func fetchNft(id: String, completion: @escaping (Result<Nft, Error>) -> Void)
    func fetchNfts(ids: [String], completion: @escaping (Result<Nfts, [Error]>) -> Void)
}

final class NftService: NftServiceProtocol {
    
    private let networkClient: NetworkClient
    
    init(networkClient: NetworkClient) {
        self.networkClient = networkClient
    }
    
    func fetchNft(id: String, completion: @escaping (Result<Nft, Error>) -> Void) {
        ...
    }
    
    func fetchNfts(ids: [String], completion: @escaping (Result<Nfts, [Error]>) -> Void) {
        ...
    }
}
```

Теперь `CollectionModel` и `CollectionViewModel` может использовать `NftService` для доступа к данным, что отделяет бизнес-логику от сетевого слоя.

Если возникают ошибки (например, сеть недоступна), NftService может возвращать их в обработанном виде, например, в виде перечисления, что позволит унифицировать сообщения об ошибках.

Пример с обработкой ошибок:
```swift
enum NftServiceError: Error {
    case networkError
    case serverError
    case unknownError
}
```

Примерный пример `CollectionModel` с использованием `NftService`

```swift
final class CollectionModel: Протокол {
    
    init(nftService: NftServiceProtocol, storage: NftStorage) {
        self.nftService = nftService
        self.storage = storage
    }
    
    func loadNft(id: String, completion: @escaping NftCompletion) {
        nftService.fetchNft(id: id) { result in
            completion(result)
        }
    }
    
    func loadCollection(ids: [String], completion: @escaping NftsCompletion) {
        nftService.fetchNfts(ids: ids, completion: completion)
    }
    
    private let nftService: NftServiceProtocol
    
}
```

2024-10-25 10:37 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +    var reloadTableView: (() -> Void)? { get set }
Исправил!

2024-10-25 10:37 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +class CatalogViewModel: CatalogViewModelProtocol {
Исправил!

2024-10-25 11:03 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +    private let sortOptionKey = "sortOptionKey"
Исправил! Вынес логику сохранения и получения опции сортировки в отдельный класс SortOptionStorage

2024-10-25 11:11 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +                .cacheOriginalImage
Пасиба))))

2024-10-25 11:20 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /Model/CollectionModel.swift
> +                    print(error.localizedDescription)
Так, весьма интересная штука. Я её себе сохранил и изучу в факультативном порядке. В этот раз реализовывать не стану, во имя экономии времени и сил, но добавлю в самом конце, как доп фичу, чтобы в портфолио смотрелось красивее!

2024-10-25 11:26 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +
Исправил! Привел код в порядок

2024-10-25 11:33 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +        print(url)
Действительно. Вместо этого я добавил уведомление пользователю о некорректном URL, лишним не будет

2024-10-25 11:35 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        dispatchGroup.enter()
Убрал!

2024-10-25 11:47 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        }
Да, исправил! Убрал лишний код

2024-10-25 11:50 UTC, slenbder commented
Исправил ошибки!
@Kirchberg Приложение как будто даже стало быстрее и лучше работать))))

2024-10-25 13:30 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +    }
По аналогии со специально написанным сервисом логирования, я реализую это либо в следующей итерации, либо уже после. Переименование класса экрана коллекции мне уже один раз сломало код, поэтому займусь этим на одной из финальных стадий проекта

2024-10-26 13:49 UTC, merged