Catalog3 3
usvladis/FakeNFT_team3 pull request #58
Opened 2024-10-28 18:19 UTC by slenbder

## Проведена работа по задачам Модуля 3: Интеграция, доработка UI и тестирование

### Задачи:

- **Реализована функциональность кнопок и взаимодействие с пользователем**
    
    - _Описание:_
        - Реализовано добавление и удаление NFT в избранное при нажатии на кнопку "сердечко" в `NFTCollectionViewCell`.
        - Реализовано добавление и удаление NFT в корзину при нажатии на кнопку корзины.
        - Обновлено состояние кнопок в зависимости от текущего состояния (в избранном/в корзине).
        - Обновлена `CollectionViewModel` для управления состоянием избранного и корзины.
    - _Оценка:_ **5 часов**; _Факт:_ 6 часов.
    
- **Интеграция с бэкендом**
    
    - _Описание:_
        - Реализованы сетевые запросы для добавления и удаления NFT из избранного и корзины.
        - Обработаны ответы сервера и обновлены данные в приложении.
    - _Оценка:_ **2 часа**; _Факт:_ 5 часов.
    
- **Тестирование и отладка**
    
    - _Описание:_
        - Проведено полное тестирование приложения на разных устройствах и версиях iOS.
        - Исправлены найденные баги и оптимизирована производительность.
        - _Оценка:_ **1 час**; _Факт:_ 1 час.
    
- **Подготовка к ревью и написание документации**
    
    - _Описание:_
        - Обновлены комментарии в коде и обеспечена его читаемость.
    - _Оценка:_ **1 час**; _Факт:_ 1 час.

2024-10-31 13:27 UTC, Kirchberg requested changes

2024-10-31 13:27 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Catalog Screen/ViewModel/CatalogViewModel.swift
> +        dispatchGroup.enter()
Использование `DispatchGroup` в данном случае избыточна, у нас только одна асинхронная таска

2024-10-31 13:27 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +    }
⚠️ При проверке выяснилось, что эти функции не срабатывают, поэтому при нажатии на сердечко и корзину не обновляются на бэке данные и соответственно не отображаются корректно в приложении

2024-10-31 13:27 UTC, Kirchberg commented on FakeNFT/Foundation/MemoryStorage/ProfileStorage.swift
> +        syncQueue.async {
⚠️ Асинхронная очередь лишняя в этом классе, достаточно просто «сохранять профиль» без нее. Тут также могут быть гонки, из-за того, что мы в разных контекстах пытаемся получить и записать значение (см. проблему читателей и писателей: https://ru.wikipedia.org/wiki/Задача_о_читателях-писателях)

Чтобы ее исправить достаточно использовать NSLock (https://developer.apple.com/documentation/foundation/nslock)

Он не позволяет читателям и писателям одновременно получать доступ к ресурсу, что помогает сохранить правильное состояние в данном случае профиля. Необходимо это поправить, приведу пример:
```swift
private let mutex = NSLock()

func doSomething() {
    mutex.lock()

    // Выполняем работу с общим ресурсом
    print("Hello World")

    mutex.unlock()
}
```

2024-10-31 13:27 UTC, Kirchberg commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        profileService.sendExamplePutRequest(likes: favoriteNFT, avatar: profile.avatar, name: profile.name) { [weak self] result in
Предлагаю уточнить название функции и внести изменения в ее нотацию. Сейчас слово "Example" может создавать впечатление, что это тестовая функция, а не часть основного функционала. Давайте подберем более описательное и ясное название, чтобы пользователям сервиса было проще понять его назначение.

2024-11-01 10:26 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /ViewModel/CollectionViewModel.swift
> +        profileService.sendExamplePutRequest(likes: favoriteNFT, avatar: profile.avatar, name: profile.name) { [weak self] result in
Исправил!

2024-11-01 10:26 UTC, slenbder commented on FakeNFT/Foundation/MemoryStorage/ProfileStorage.swift
> +        syncQueue.async {
Исправил!

2024-11-01 10:26 UTC, slenbder commented on FakeNFT/Scenes /Catalog/Collection Screen /View/CatalogDetailsScreenViewController.swift
> +    }
Исправил!

2024-11-02 08:19 UTC, Kirchberg approved these changes
Работа допущена до мерджа с основной веткой. Мердж должен происходить вместе со всей группой.

Возвращайся в следующей работе с вмердженными эпиками коллег. 
Эту часть работы нужно оформить в пул реквесте (develop->master), вся команда присылает на проверку одну и ту же ссылку. 

Нужно будет приложить скринкаст с демонстрацией своего эпика на симуляторе: 
рекомендую ссылку складывать не только в ПР, но и в Readme под описанием твоего эпика.

2024-11-02 08:19 UTC, Kirchberg commented on FakeNFT/Foundation/MemoryStorage/ProfileStorage.swift
🔥

2024-11-04 11:26 UTC, merged